### ISSUE TITLE
BluRay and DVD case border option for movies

### ISSUE THREAD

**Issue by jingai** [stoli/Metropolis#182]
Requested by protocol77 at http://forum.xbmc.org/showthread.php?tid=99317&pid=1191763#pid1191763

**Comment by MacGyverr** [comment]
Added a newer commit to work with the recent view changes made by Jingai.
https://github.com/MacGyverr/Metropolis/commit/a0e64445e294f6c08bfbd341e2ff46b71a3c79d6

**Comment by jingai** [comment]
This isn't going into official.
