### ISSUE TITLE
Support for script.extendedinfo

### ISSUE THREAD

**Issue by jingai** [stoli/Metropolis#217]
http://forum.xbmc.org/showthread.php?tid=160558

**Comment by jingai** [comment]
http://forum.kodi.tv/showthread.php?tid=160558
https://github.com/phil65/script.extendedinfo/blob/master/README.txt

**Comment by romanoh** [comment]
This will put this Theme on the Top(more that it is now), cant wait.

**Comment by jingai** [comment]
https://github.com/MacGyverr/skin.metropolis-personal/commit/11ac62a7a5ca0022a8cf2879b049881033f73de2
