### ISSUE TITLE
Support for last.fm scrobbler love and ban

### ISSUE THREAD

**Issue by hetas** [stoli/Metropolis#246]
There's a new scrobbler add-on for last.fm for Gotham (https://github.com/XBMC-Addons/service.scrobbler.lastfm) with love and ban functionality. Current love/ban buttons in Metropolis don't work with that.

I don't know if these buttons are working with some other add-on. Probably not. I assume those were for the built-in last.fm support which was dropped.

I got love and ban working by editing MusicOSD.xml but I don't know what to do with the enable-tags for the buttons.

**Comment by jingai** [comment]
See Transparency! skin for an example implementation.
