### ISSUE TITLE
Use Skin Shortcuts addon for custom home items

### ISSUE THREAD

**Issue by jingai** [stoli/Metropolis#256]
http://forum.xbmc.org/showthread.php?tid=178294

MacGyverr's had a stab at this:  https://github.com/MacGyverr/Metropolis/tree/helix-custommenu-rewrite

**Comment by jingai** [comment]
Noting to update the features at http://kodi.wiki/view/Add-on:Metropolis when this is complete.

**Comment by jingai** [comment]
Just noting this here:

http://forum.kodi.tv/showthread.php?tid=213669&pid=1890929#pid1890929

**Comment by jingai** [comment]
Getting closer on this.. few things remain:

* everything in shortcuts/overrides.xml and 720p/script-skinshortcuts.xml needs to be localized
* media overlay for music overlaps the widgets
* i want a custom widget for addons to retain the old icon-based list we had before
* skin for script.skinshortcuts is behaving.. oddly.. need to see if I missed one of your commits or something

**Comment by MacGyverr** [comment]
"media overlay for music overlaps the widgets"  My version solves this for the home menus, I just need to add the settings menus to the list of conditionals of where not to display. Cut and paste as needed. :)

**Comment by jingai** [comment]
Which version are you referring to?  The menurefactor branch was showing it overlapping because the condition in Includes_MediaOverlay.xml hadn't been updated.

**Comment by MacGyverr** [comment]
I stopped updating that branch because I was afraid it was getting too far off of the official for you to be able to merge properly.  Do you have an official Menu-refactor branch that I can fork off of?  Do you have an offline one that is now equal to it?   I was updating my personal version with little fixes until you had an official branch with the menu-refactor, that way I could have an idea for code fixes that might come up with the switch to Jarvis.

**Comment by jingai** [comment]
Aye, that's why I've been watching your commits on your personal version :)

I will be pushing it all into master soon.  I do have a branch at jingai/skin.metropolis currently, but I'm force-pushing it currently, so I don't recommend branching from there.. in fact, I'll go ahead and merge this in so you can help out if you want to.  I'll make separate Issues for each thing that still needs to be completed.

It's almost done really.  Last remaining issues/questions:

* The strings in shortcuts/overrides.xml need to be localized.  Kodi team won't accept the PR without this.

* Need to call skinshortcuts with buildxml onunload of the customize dialog?  I notice it sometimes doesn't trigger for some reason when going back to Home after making a change.  I think this is why you did it.

* Media Overlay overlaps widgets.  FYI, I get around having to use any special conditions for the settings dialog text (PlotBox) by dynamically adjusting the PlotBox size if the overlay is present.  The only conditions remaining are 1) mediaflags present (this is easy), and 2) widget is currently visible.

* Playlist widget fanart is squished into poster width.  Should match the other widgets, where they extend the width if it's fanart and not a poster.

* Playlist widget needs to show artwork always in Home1 view.  Widgets never disappear in Home1.

* Want to support multi-image for backgrounds.  Likewise, I want to allow the user to change the icon (for Home2).

* I'd like to retain the old Addons "widget", displaying 5 icons horizontally.  This can wait for a future release though.

**Comment by jingai** [comment]
It's all sitting at https://github.com/stoli/Metropolis/tree/refactor now.  I'm going to make separate issues for the things that need to be done before I can release.

I won't force-push to that branch, so you're safe to branch from there if you want.

**Comment by jingai** [comment]
All Issues created.  Closing this now.
