### ISSUE TITLE
Add listitem.episode and listitem.premiered to List view for Addons

### ISSUE THREAD

**Issue by jingai** [stoli/Metropolis#258]
Show the Episode Number and Air Date of items for addons.

**Comment by jingai** [comment]
See Confluence for an example of this.

**Comment by jingai** [comment]
Ok so this is only for addons.. it needs to show the episode and premier date in the same places it does for items in the video library.

List view should perhaps show the thumbnail in square aspect as well, since most addons seem to not be posters.. but I'm not sure.

**Comment by MacGyverr** [comment]
The issue is that Kodi creates the episode info straight into the ListItem.Label, you can create a similar view by piecing it together from elements, but it requires a lot of conditionals.

**Comment by jingai** [comment]
Yeah, I remembered this after I looked at it again the other day.. I would like to offer more views and information for addons, but it's seriously difficult to test all of the conditions since all addons seem to provide similar content in different ways..

**Comment by MacGyverr** [comment]
Maybe some conditional variables could work their magic.  You know what I mean, build one view, and just define the labels and textures separate.  The code is smaller, and allows for adding new elements quicker. (no rewrites for every new thing)

**Comment by jingai** [comment]
Aye, I'll be looking at it closely since I want to make the data displayed as uniform as possible across all views anyway.

**Comment by jingai** [comment]
Use ListItem.Premiered instead of ListItem.Year for the following views when in Episodes:

* Gallery Fanart
* Landscape

**Comment by jingai** [comment]
Really this whole problem would go away if addon developer's would just flag their freaking content correctly..

**Comment by jingai** [comment]
Pushing this off.. I know Confluence has workarounds in place for this, but I really think these kinds of workarounds belong in the addons (i.e., setting the current content type correctly).  Not going to close the issue.. but I'd rather not prioritize it either since it really feels like a Not My Problem kind of thing.

**Comment by jingai** [comment]
To add to this, look at the YouTube addon as an example of one that does it correctly.

**Comment by jingai** [comment]
Ok, I caved.  It will show the episode on the list item now, but.. there are now some shows within addons that set both season and episode to 1 (or some arbitrary value) for everything.. so prepare for that backlash I guess.

Fix it for some and break it for others.. ultimately though, this is up to the addon authors to deal with.  The way I'm handling it now is proper.

Reports of superfluous and incorrect season/episode numbers on the items I can at least now just pass the buck to the addon author.
