### ISSUE TITLE
Use service.library.data.provider instead of Skin Widgets

### ISSUE THREAD

**Issue by jingai** [stoli/Metropolis#276]
Compare the two.

**Comment by MacGyverr** [comment]
To see this in action check out here:
https://github.com/MacGyverr/skin.metropolis-personal/commit/27b62fffd3a63c291bba914c770e36d596a46c89
I noticed it used virtually the same method as extendedinfo so I saw an opportunity to cut down some code.  The Homedeck.xml is now only 1000 lines long (most of that is the weather widget)
