### ISSUE TITLE
Updates notification addons dont show

### ISSUE THREAD

**Issue by romanoh** [stoli/Metropolis#290]
Hello, great work stoli,
i have an Ouya and the Updates notification addons don't show, i don't now if it is my problem or  Metropolis.

**Comment by jingai** [comment]
Metropolis won't affect an addon's behavior.  It's a problem with Kodi/XBMC, the addon itself, of configuration thereof.

**Comment by romanoh** [comment]
I meant the little window that appears on home when an addon is update, i cant tell witch addon where updated.

**Comment by jingai** [comment]
Which version of Kodi and Metropolis are you using?

Post a screenshot showing the issue please.

**Comment by romanoh** [comment]
ha its working, but its so fast i cant even read it, can you please put more seconds to show?
