### ISSUE TITLE
Add language background flag to CC Media Flag

### ISSUE THREAD

**Issue by jingai** [stoli/Metropolis#292]
Country flag indicating the original audio language of the movie/show.

https://github.com/MacGyverr/skin.metropolis-personal/commit/448a0fec81a0fb4c2dabc58dede90986e1e4c05f

https://github.com/MacGyverr/skin.metropolis-personal/commit/e03e17fac889f0ef16d50cbf4f25587ffe212fb6

**Comment by MacGyverr** [comment]
And this one,
https://github.com/MacGyverr/skin.metropolis-personal/commit/a7a287803dae26e9958458fc0cc69d5c06f0c458
I forgot the mask in the commit to the git.
