### ISSUE TITLE
Fix dangling bit at the end of the OSD Progress Bar

### ISSUE THREAD

**Issue by jingai** [stoli/Metropolis#293]
No idea what's causing it, but it's finally annoying me enough to fix it..

**Comment by MacGyverr** [comment]
You mean the weird bit at the bottom, like an opposite shadow just near the end?

**Comment by MacGyverr** [comment]
![screenshot000](https://cloud.githubusercontent.com/assets/6500800/5749440/501f682a-9c49-11e4-82a5-070b4e218f19.png)

**Comment by jingai** [comment]
Yeah.  For some reason, adding "<reveal>true</reveal>" to all the progress bars fixes it.  Not exactly sure why, but... oh well, it works lol.

**Comment by MacGyverr** [comment]
It's not in the graphics, I checked.

**Comment by jingai** [comment]
Yeah, I did too.  It's something to do with the reveal tag, but I'm not 100% sure what that tag is even for.  The wiki says "If set to true the midtexture will reveal itself instead of stretching to fill the gap (works best when its the same size as texturebg)".  I'm guessing the old behavior (like, pre-Gotham or so) was to default to true, and at some point they exposed the tag and defaulted it to false.  I don't really know what it's *supposed* to do, but it doesn't show the artifact if it's set to true.
