### ISSUE TITLE
CoverFlow view type doesn't show posters in Apple iTunes Trailers addon

### ISSUE THREAD

**Issue by jingai** [stoli/Metropolis#295]

**Comment by MacGyverr** [comment]
![screenshot000](https://cloud.githubusercontent.com/assets/6500800/5768179/b82e7878-9d0e-11e4-821f-58201de9cf70.png)

I wonder why?

**Comment by MacGyverr** [comment]
I may have fixed this, but at least it's smaller (I deleted 3000 lines, it's now a fourth the original size).
It should allow for easier artwork changes.

![screenshot000](https://cloud.githubusercontent.com/assets/6500800/5806757/7deae014-a01c-11e4-8c1e-77d86d2deb25.png)

**Comment by jingai** [comment]
Cool, I'll look at it when I get a chance.

Noting the commit here for reference:  https://github.com/MacGyverr/skin.metropolis-personal/commit/d850aa9be326a00a4ace3b0a5775712c9454ec83

**Comment by MacGyverr** [comment]
It might have slowed it down though, I suck at optimization so you might need to see if it moves too slowly.  Hopefully you can see a way to speed it up.  It works great on my i7 :)

**Comment by jingai** [comment]
I'll look at it closely, especially since a lot of folks are running on set-top boxes with minimal hardware.

**Comment by jingai** [comment]
Had a chance to look at it.  Really good work!

The only issue I see is it doesn't fallback to DefaultThumb.png while it's caching the next images.  This is easiest to see in the Trailers addon.

**Comment by jingai** [comment]
Well I'm not going to worry about the caching thing too much.  But there are a couple more issues.

I have test library here that only has 4 movies.  On this view, it doesn't always show all 4 at once depending on where the user is in the list.

The second issue is that if the item has no Poster, ListItem.Icon defaults to a screencap from the video, which obviously doesn't have the correct aspect ratio:

![screenshot000](https://cloud.githubusercontent.com/assets/338896/5979402/67385188-a875-11e4-8e0a-6b2d962f342f.png)

**Comment by jingai** [comment]
Ok.. weird.. I restarted Kodi and it's no longer doing the first thing.. something must have gone wonky on the skin reload (F5).

**Comment by MacGyverr** [comment]
Is the speed ok for you though?  I hadn't tested it on only 4 items, but I'm sure it's a simple fix, I'll look into it tomorrow.  I was concerned about the speed, my i7 does a fine job, but my single core Atom, not so much.  Maybe just me though.

**Comment by jingai** [comment]
I don't see any particular reason it should be slower than it was before, just from looking at the code.  To be honest, the Coverflow view has always been a bit sluggish on minimal hardware anyway.

Utilizing the preloaditems tag may help, not sure.  The old one didn't use it though.  Are you finding that the new view is significantly slower on the machine with the Atom processor?

**Comment by jingai** [comment]
So I'm guessing the original problem was that the iTunes Trailer addon isn't setting ListItem.Art(Poster), but it is setting ListItem.Icon?

If that's the case, the simple thing to do is to only utilize ListItem.Icon if inside an addon currently.

**Comment by jingai** [comment]
Working from https://github.com/stoli/Metropolis/tree/coverflow

Don't pull that into your master yet though, as I'm going to force-push updates.  Just create a new local tracking branch.

**Comment by jingai** [comment]
Noting here that the watched overlay flag should be on the lower-left corner of the image, not near the title text.

**Comment by MacGyverr** [comment]
Using the variables starting at line 256 solves the image issue, but I was hoping for the huge size reduction and a more easily movable coverflow "blob".

**Comment by jingai** [comment]
Closing this and opening Issue #302 for the problem with short lists.
