### ISSUE TITLE
Button selection highlight line goes behind profile image in Edit Profile dialog

### ISSUE THREAD

**Issue by jingai** [stoli/Metropolis#316]
![screenshot013](https://cloud.githubusercontent.com/assets/338896/6154658/61f444b8-b1fb-11e4-96a0-f380e6773600.png)

**Comment by MacGyverr** [comment]
https://github.com/MacGyverr/Metropolis/commit/12210365d5593fa6e2b19317b73e32ecdd74fe85

![screenshot005](https://cloud.githubusercontent.com/assets/6500800/9156477/b6a9379e-3edb-11e5-81f4-fab95a9c35b6.png)

**Comment by jingai** [comment]
To be honest, I think it looks fine the way it was, and matches the rest of the left side buttons in the skin better.  What do you think?

**Comment by MacGyverr** [comment]
I think it looked fine before. 

What about moving the icon and description down below in the info bar?
![b6a9379e-3edb-11e5-81f4-fab95a9c35b6](https://cloud.githubusercontent.com/assets/6500800/9973318/32025128-5e71-11e5-8c9c-1bfe8eedc36e.jpg)

Or moving the ok buttons lower?

![b6a9379e-3edb-11e5-81f4-fab95a9c35b6-2](https://cloud.githubusercontent.com/assets/6500800/9973327/452c86f6-5e71-11e5-9084-6efcdca3ae83.jpg)

**Comment by jingai** [comment]
I think it looks weird personally any other way than it was lol.  It's not a huge deal though.

**Comment by MacGyverr** [comment]
I like the old way, going behind the picture seems kind of artsy.   What above or below?
![b6a9379e-3edb-11e5-81f4-fab95a9c35b6-3](https://cloud.githubusercontent.com/assets/6500800/9975072/c5388a7a-5ead-11e5-99a0-343025b65045.jpg)

**Comment by jingai** [comment]
Yeah, honestly I don't think it looks 'wrong' the way it was.. it looks intentional to me, unless of course one is aware of this discussion ;)

Going to leave it as it was.
