### ISSUE TITLE
Metropolis + RCB glitch?

### ISSUE THREAD

**Issue by Haris1977** [stoli/Metropolis#317]
Greetings.

Nice skin guys! Keep the good work:)

My problem is that i cannot launch RCB (Rom Collection Browser) neither from GAMES menu nor FAVORITES menu. I can only launch it from addons. Is it a known bug?

**Comment by jingai** [comment]
I abandoned RCB some time ago and switched to Advanced Launcher.  I know RCB needs some skin support to work properly, and work was started on that, but never finished.
