### ISSUE TITLE
Adding origin country info in ViewDetailsGenreYearDurEpsUnwatched include

### ISSUE THREAD

**Issue by mihvel** [stoli/Metropolis#319]
I think it would be very useful to have info about video origin country in Movie views. I did changes by myself in ViewDetailsGenreYearDurEpsUnwatched include, so if you find it's OK to support this feature you can check it here and adopt it if you like: http://www8.zippyshare.com/v/z5lC7jIj/file.html

**Comment by jingai** [comment]
I responded to your comment on the kodi forums already, but for some reason the post didn't show..

Anyway, this information is already provided in the form of a Media Flag whose icon is a representation of the country of the original audio track associated with the selected item.  I don't think we need to display it twice.

**Comment by mihvel** [comment]
Well, as you said, what you are showing in the main view with the country flags is not the origin country but the default audio language (which is maybe not the same as original audio language! eg. if the movie is dubbed). This info is taken from the video file and very often it is not contained in the file, especially for the avi video format.
For sure, I can understand that you can not accept every suggestion from the users. I can easily patch new skin realises with my changes. But maybe you can reconsider your decision :). Just try my changes and take a look. 
Whatever you decide thank you   for the quick response and just continue with excelent work on the best Kodi skin!

**Comment by jingai** [comment]
I consider every suggestion carefully.  I guess the issue with this one is that the info is available if you need it (via the DialogVideoInfo dialog) and I just can't really see why you'd need to see it with one fewer keystroke.

The problem with putting information in that particular space is that there is limited real estate, more so for some views than others.  So I have to very carefully pick and choose what information I think is relevant to display there vs the Info dialog.

Additionally, the country information won't fit on every view, and consistency is important to me.  See the three List views for an example of this.
