### ISSUE TITLE
Captcha letters hiding.

### ISSUE THREAD

**Issue by romanoh** [stoli/Metropolis#320]
Hi there,
i don't now if this is an issue or not from your skin, if not please erase this.

The problem is described here: https://github.com/tknorris/salts/issues/82#issuecomment-77764018

Is there a solution?
Thank you very much @stoli

**Comment by jingai** [comment]
It sounds like it's not necessarily an issue per se, just that he pops up an image on-screen in the upper-left corner?  If so.. yeah.. that's where the progress dialog shows in Metropolis.

**Comment by jingai** [comment]
This isn't my issue any more than it is of the addon author.
