### ISSUE TITLE
Rating info not displayed in Video Info

### ISSUE THREAD

**Issue by jingai** [stoli/Metropolis#324]
Path displays fine if that option is turned on, but rating info isn't showing for some reason.

**Comment by MacGyverr** [comment]
It looks like it works as you directed.  It only shows if it's a movie & rating is not empty but only if the rating is not just the rating but the rating and a description (unless it's set to something non-standard), so long as show-path isn't set.

![screenshot003](https://cloud.githubusercontent.com/assets/6500800/9156283/dadb28c2-3ed4-11e5-81f5-9e6dfce3843f.jpg)

![screenshot004](https://cloud.githubusercontent.com/assets/6500800/9156284/e0f25e2e-3ed4-11e5-8faf-7407f6270f22.jpg)

**Comment by jingai** [comment]
I guess I'll just show it unconditionally then, especially since what's there only applies to US ratings.
