### ISSUE TITLE
Skinning for script.skinshortcuts editor (script-skinshortcuts.xml)

### ISSUE THREAD

**Issue by jingai** [stoli/Metropolis#340]
Decided to break this out from the main skin shortcuts commit.

**Comment by jingai** [comment]
Changed my mind.. it's kind of almost necessary for basic functionality.

**Comment by MacGyverr** [comment]
Mine is ok, the new official one inside the script as an example is a train wreck.

**Comment by jingai** [comment]
No kidding, his is pretty awful lol.

For some reason the one I had gotten from you wasn't working right on another machine.  I took the version from your fork though and it seems to be working right here.  Going to test things on the other machine in a bit.

Just a few more little issues and strings to localize.. then can release for Helix at least.  Isengard is next.
