### ISSUE TITLE
Horizontal Icon widget

### ISSUE THREAD

**Issue by jingai** [stoli/Metropolis#347]
![](https://cloud.githubusercontent.com/assets/338896/10062402/4c091436-6230-11e5-8851-f2f84e523c90.png)

Should show a horizontal list of 4-5 icons configured by the user.  Like what we had before the addition of Skin Shortcuts.

@MacGyverr added this in https://github.com/MacGyverr/skin.metropolis-personal/commit/115aee52c538a5a3c0f146458022f6cda6de2b5d; however, I want it to be configurable per-widget, and Kodi does not currently provide a way to use variables in Settings names.  There is some discussion about this here:  http://forum.kodi.tv/showthread.php?tid=240147

**Comment by MacGyverr** [comment]
This is what it looks like in mine, is this what you mean?

![screenshot002](https://cloud.githubusercontent.com/assets/6500800/10060238/021c1132-6250-11e5-8906-7b71be6f540b.jpg)

I have been adding all kinds of widgets as a test to see what can and can't be supported.

**Comment by jingai** [comment]
No, not exactly.  I mean a widget that displays a horizontal list of 4-5 (whatever fits) icons that the user can customize.  Like it was before.

**Comment by MacGyverr** [comment]
Visual example?

**Comment by jingai** [comment]
I will later.. in the middle of editing, and getting a screenshot would require that I revert all these changes.

**Comment by jingai** [comment]
![screenshot000](https://cloud.githubusercontent.com/assets/338896/10062402/4c091436-6230-11e5-8851-f2f84e523c90.png)

**Comment by MacGyverr** [comment]
I just fixed this in 
https://github.com/MacGyverr/Metropolis/commit/dda75fc00269dfda4e7f5481f63b823b69f43c13

![screenshot004](https://cloud.githubusercontent.com/assets/6500800/10104671/2cf0a04c-63ab-11e5-96be-b7ae33b94cc5.jpg)

**Comment by jingai** [comment]
@MacGyverr pointed out that the newer Skin Shortcuts script has support for additional per-widget properties that we can maybe make use of to make this a configurable option.
