### ISSUE TITLE
Skin Shortcuts builds menu XML twice after leaving script-skinwidgets.xml window

### ISSUE THREAD

**Issue by jingai** [stoli/Metropolis#348]
Only when there is a change to the furniture.  Not sure why, but it's a tad annoying.

**Comment by jingai** [comment]
@Ignoble61, if you have a spare moment at any time, would you mind taking a glance at the Skin Shortcuts implementation on the refactor branch here?  Just wanting to verify we didn't do anything grossly wrong, since the documentation for it is a bit scattered.

**Comment by Ignoble61** [comment]
I'll download and play with it when I'm back in front of my own computer next week. Having had a very quick peak at the code, can I suggest two very minor changes:-

* add the skinshortcuts build line to `<onload>` in home.xml (users switching from another skin-shortcuts-utilising-skin are more likely to go to the home page before the skin settings page, and so won't see their shortcuts)
* Remove the skin shortcuts build line from button 10 in script-skinshortcuts.xml - whilst it's a fine idea to trigger a menu build as that dialog closes, skin shortcuts only saves the shortcuts when the dialog closes, and may not have finished that before it starts building a menu.

Anything you'd particularly like me to look at? (And any areas of the docs that are particularly confusing? I've begun a - very very slow - re-writting-in-a-wiki-style for them, so it's a good time to get any feedback about them in ;))

**Comment by jingai** [comment]
* Home.xml does have the build line in ```<onload>``` on line 4.  Or is there something wrong with it?
* Will remove it from script-skinshortcuts.xml.  Might be the cause of #348.

As for the documentation.. well, it's hard to say exactly, but I just didn't feel like I had a very good overall picture of how it worked from the documentation alone.  Probably a more thorough overview at the beginning, with maybe an example step-by-step (barebones, but including main menu and one submenu) implementation, would be good.

Regarding what I'd like you to look at.. nothing in particular, really.  Just wanted you to glance at it and make sure nothing was horribly wrong lol.

**Comment by Ignoble61** [comment]
My bad on the home.xml - that's what I get browsing code on github :blush: Build line there is absolutely fine.

I don't know if you've seen the examples in README.txt - the idea of them is to show the barebones, or are you saying you would like to see more detail? (Either way, they haven't been updated in a very long time, so at the very least need a review to check they're still 100% correct, and I can see from a quick glance there is some now-outdated info in that file)

OK, will have a general play when I get chance :)

**Comment by jingai** [comment]
I think the out-dated info was honestly most of my problem.  I just felt like I didn't have a good grasp on it until I read through the forum thread as well, where I "followed the script's development".

Sorry I'm not being more specific.  It was just small feelings of doubt as I went along is all.

**Comment by Ignoble61** [comment]
Not a problem :) As I say, updated docs are coming - the idea of them is to split every topic (including the bare-bones) out into its own section which will hopefully make things a lot clearer - if you don't mind, when they're close I'll hit you up to take a look through. I'd also love at some point (if I ever find the time and the correct method) to fork Confluence and maintain it as an example skin, but that's a pipe dream for now.

**Comment by jingai** [comment]
I'll definitely have a look through them when you're done.  Just ping me here or on the forums when the time comes.

And a working example that's always up-to-date (fork of Confluence) would be perfect indeed.

**Comment by MacGyverr** [comment]
Did you intend to not let the user alter the sub-menus?
https://github.com/stoli/Metropolis/blob/refactor/720p/script-skinshortcuts.xml#L333

**Comment by jingai** [comment]
Uh, I didn't add that, but I'll check.

**Comment by jingai** [comment]
I don't know why that's there, but it seems to work here.  Are you having an issue with it?
