### ISSUE TITLE
Consider support for Super Favourites add-on

### ISSUE THREAD

**Issue by jingai** [stoli/Metropolis#351]
See: http://forum.kodi.tv/showthread.php?tid=192662

**Comment by MacGyverr** [comment]
I sort of did this, it sort of sucks.  (It may be the way I called the plugin, but it looks like the author needs to put some more time into how it builds it content lists)
https://github.com/MacGyverr/skin.metropolis-personal/blob/master/shortcuts/overrides.xml#L113
https://github.com/MacGyverr/skin.metropolis-personal/blob/master/720p/Includes_Variables.xml#L147

Fyi, under the new system, that is all it takes to add a widget. Those 2 lines. :)

This area just fixes the label format if we don't like what the plugin spits out natively.
https://github.com/MacGyverr/skin.metropolis-personal/blob/master/720p/Includes_Variables.xml#L166

**Comment by jingai** [comment]
Yup, it is easy to add widgets (provided I want to display them the same way, at least), but this is just a note to have a look at it before I blindly add it in.

I'm still trying to decide if I want to take a proactive approach to adding widgets in, or wait for people to post on the forums asking for them.

**Comment by jingai** [comment]
It does sort of suck.  Ignoring this one.
