### ISSUE TITLE
Mouse and Touch support

### ISSUE THREAD

**Issue by jingai** [stoli/Metropolis#353]
People keep begging for it, so need to do this eventually.

**Comment by MacGyverr** [comment]
This is going to suck.
I recommend that you ask the users what should do what.  Buttons and sliders are obvious, but commands that lack buttons need to be whatever they are used to (or expect), like swipe left is settings or swipe right is back (or up, or tap 4 times), I have no idea, but they might.  I would try to get a consensus on what they already expect.

**Comment by jingai** [comment]
Hence why it doesn't have a milestone attached to it.

I'm honestly kind of waiting for someone who even uses the skin with on a tablet device to give me some direction.  If I ever get really bored, I might install it on my phone or something, but I'm rarely that bored... ;)
