### ISSUE TITLE
Use new widget selector in script.skinshortcuts 0.6.0+

### ISSUE THREAD

**Issue by jingai** [stoli/Metropolis#357]
Replacing button ID 309 with 312.  Check documentation for required changes.

https://github.com/BigNoid/script.skinshortcuts/blob/master/resources/Advanced%20Usage.txt

**Comment by MacGyverr** [comment]
it looks like the stuff we do in variables is now moved to overrides.xml in a new format, and a common string is used as the content instead.

**Comment by jingai** [comment]
Yep.  I'll get back on this after the basic Kodi 15 support is in.  Shooting for Helix release this weekend, and Isengard beta at the same time, or a few days after.

**Comment by MacGyverr** [comment]
Good luck, scream if you need anything, pvt msg me in kodi forum as needed.

**Comment by jingai** [comment]
I have some time finally, so I should be OK.  I may want to run things by you for your opinions though :)
