### ISSUE TITLE
Option to configure number of rows shown in Banner view

### ISSUE THREAD

**Issue by jingai** [stoli/Metropolis#379]
As MacGyverr did over here: https://github.com/MacGyverr/Metropolis/commit/273c7e58667d25c337fb5c7b19e60f1b8f59b50c

But I dislike that it returns to the previous window after it is changed.  That will need to be fixed before I include this.

It also cannot be 5 rows, since that eats into the Heading space.  4 is the maximum.

**Comment by MacGyverr** [comment]
I return to the previous window on purpose because I couldn't change an include without a screen refresh.  It was the only way to work, I just figured rather than have the user maybe not understand that the screen isn't going to change after they make their change, I would force it.

**Comment by jingai** [comment]
I understand why you did it, I just want to explore alternatives.

**Comment by jingai** [comment]
I keep wavering on this one because.. the default is 3; 5 is impossible (within design constraints); and 1 and 2 just seem silly to me.. that leaves 4 rows.

Maybe just making it 4 rows would satisfy people, I don't know.
